### ISSUE TITLE
Use with other PPX's

### ISSUE THREAD

**Issue by zbaylin** [janestreet/ppx_optcomp#9]
Hello, I have a separate PPX called `ppx_os` ([Rolltrax/ppx_os](https://github.com/Rolltrax/ppx_os)) that I would like to use in conjunction with `ppx_optcomp`.

If I have this in ocaml:
```ocaml
[%%define os [%operating_system]]
```
I get the error
```
Error: optcomp: expression not supported
```
I was under the assumption that I could use `ppx_optcomp` with other ppx's to determine things like environment variables and the like. Am I mistaken, is my syntax wrong, or is there something else that I'm missing?

Thank you!

**Comment by lpw25** [comment]
ppx_optcomp deliberately registers itself as a preprocessing pass with ppxlib, so that it is run before other ppxes. My understanding is that this is so that attributes and extensions that are dropped by conditional compilation are not processed by other ppxes (where they might error).

I think this is unlikely to change, so I'm going to close this issue. Sorry for the slow and not particularly helpful response.

**Comment by zbaylin** [comment]
No worries, that's helpful information. Thanks!
